import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Link from "next/link";
import MobileNav from "./components/MobileNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MobileNav>{children}</MobileNav>
        <Header>
          <Link href="/">     <button className="pt-[2px] pr-4 pl-4 mr-4 outline  outline-white hover:text-sky-400 hover:bg-white rounded-full transition duration-300 font-distancia text-md">Home</button></Link>
          <Link href="/about"><button className="pt-[2px] pr-4 pl-4 mr-4 outline  outline-white hover:text-sky-400 hover:bg-white text-white rounded-full transition duration-300 font-distancia text-md">About</button></Link>
          <Link href="/resume"><button className="pt-[2px] pr-4 pl-4 mr-0 outline outline-white hover:text-sky-400 hover:bg-white text-white rounded-full transition duration-300 font-distancia text-md">Resume</button></Link>
        </Header>
        {children}
      </body>
    </html>
  );
}
